openapi: 3.0.3
info:
  title: Library API
  version: 1.1.0
  description: STD22001
servers:
  - url: https://library.com
paths:
  /books:
    get:
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - $ref: '#/components/parameters/queryPagination'
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        - in: query
          name: releaseDate
          description: Filter by the date of the release date range
          required: false
          schema:
            type: string
            format: date
      responses:
        200:
          description: The list of filtered books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    put:
      summary: Create or update a list of books
      operationId: createUpdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Book'
      responses:
        200:
          description: The list of created or updated books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /books/{bookId}/authors/{authorId}:
    put:
      tags:
        - books
      summary: Attach author to a book
      description: Attach author to a book by ID.
      operationId: attachAuthorToBook
      parameters:
        - in: path
          name: bookId
          description: The ID of the book
          required: true
          schema:
            type: string
        - in: path
          name: authorId
          description: The ID of the author
          required: true
          schema:
            type: string
      responses:
        200:
          description: Author successfully attached to the book
  /authors:
    get:
      summary: Get all authors
      description: Get a list of all authors.
      operationId: getAuthors
      parameters:
        - $ref: '#/components/parameters/pathPagination'
        - in: query
          name: authorName
          description: Filter authors by name
          required: false
          schema:
            type: string
      responses:
        200:
          description: The list of filtered authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
    put:
      summary: Create or update authors
      operationId: createUpdateAuthors
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Author'
      responses:
        200:
          description: The list of created or updated authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
    delete:
      summary: Delete authors
      operationId: deleteAuthors
      responses:
        200:
          description: Authors successfully deleted
  /books/authors:
    put:
      tags:
        - books
        - author
      summary: Attach authors to books
      description: Attach multiple authors to multiple books by ID.
      operationId: attachAuthorsToBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/UpdateBookAuthor"
      responses:
        200:
          description: Authors successfully attached to the books

components:
  parameters:
    queryPagination:
      $ref: '#/components/parameters/queryPagination'
    pathPagination:
      $ref: '#/components/parameters/pathPagination'
  schemas:
    Book:
      $ref: '#/components/schemas/Book'
    crupdateBooks:
      $ref: '#/components/schemas/crupdateBooks'
    UpdateBookAuthor:
      $ref: '#/components/schemas/UpdateBookAuthor'
    Author:
      $ref: '#/components/schemas/Author'
